name: crewmeister_test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.4

flutter:
  uses-material-design: true

  assets:
    - assets/json_files/
